server:
  port: 8761

eureka:
  instance:
    hostname: peer1
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8760/eureka/
    registry-fetch-interval-seconds: 30
  server:
    #关闭自我保护机制
    enable-self-preservation: false
